apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dovecot.deployment.name" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "dovecot.deployment.name" . | quote }}
{{ include "mum.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.dovecot.deployment.replicaCount }}
  selector:
    matchLabels: 
      app.kubernetes.io/name: {{ include "dovecot.deployment.name" . | quote }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dovecot.deployment.name" . | quote }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "dovecot.deployment.name" . | quote }}
        image: "{{ .Values.dovecot.deployment.image.repository }}:{{ .Values.dovecot.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.dovecot.deployment.image.pullPolicy }}
        ports:
        - { name: lmtp, containerPort: 24, protocol: TCP }
        - { name: pop3, containerPort: 110, protocol: TCP }
        - { name: imap, containerPort: 143, protocol: TCP }
        - { name: imapssl, containerPort: 993, protocol: TCP }
        - { name: pop3ssl, containerPort: 995, protocol: TCP }
        - { name: managesieve, containerPort: 4190, protocol: TCP }
        env:
        - { name: "DB_HOST", value: {{ include "mariadb.service.address" . | quote }} }
        - { name: "DB_NAME", value: {{ .Values.mariadb.db.name }} }
        - { name: "DB_USER", value: {{ .Values.mariadb.db.user }} }
        - { name: "DB_PASSWORD", valueFrom: { secretKeyRef: { name: "db-secret", key: "mariadb-password" }} }
        volumeMounts:
        - name: "mail-volume"
          mountPath: /srv/mail
        readinessProbe:
          tcpSocket:
            port: imap
            initialDelaySeconds: 5
            periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: imap
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
      - name: "mail-volume"
        persistentVolumeClaim:
          claimName: {{ include "dovecot.pvc.name" . | quote }}