apiVersion: v1

kind: ConfigMap
metadata:
  name: mum-config
  namespace: default
data:
  APP_NAME: "MUM"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://192.168.99.100"
  TIMEZONE: "Europe/Berlin"

  LOG_CHANNEL: "stack"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"
  QUEUE_DRIVER: "sync"

  MAIL_DRIVER: "smtp"
  MAIL_HOST: "127.0.0.1"
  MAIL_PORT: "587"
  MAIL_USERNAME: ""
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: ""
  MAIL_FROM_NAME: ""

  PASSWORD_MIN_LENGTH: "8"
  VALIDATE_LOCAL_PART: "true"
  ALLOW_UNICODE_LOCAL_PART: "true"
  VALIDATE_DOMAIN: "true"
  VALIDATE_DOMAIN_AS_HOSTNAME: "false"

  HASHING_DRIVER: "bcrypt"

  DOMAINS_QUOTA: "0"
  DOMAINS_MAX_QUOTA: "null"

  SYSTEM_HEALTH_CHECK_SERVICES: "false"
  SYSTEM_HEALTH_CHECK_FREQUENCY: "5min"
  SYSTEM_HEALTH_MAX_ENTRIES_INCIDENT_HISTORY: "100"

  SIZE_MEASUREMENTS_DELETE_OLD: "true"
  SIZE_MEASUREMENTS_DELETE_AFTER_MONTHS: "12"
  SIZE_MEASUREMENTS_DELETE_AFTER_WEEKS: "0"
  SIZE_MEASUREMENTS_DELETE_AFTER_DAYS: "0"

  ENABLE_INTEGRATIONS: "false"
  INTEGRATIONS_ENABLE_SHELL_COMMANDS: "false"
  INTEGRATIONS_ENABLE_WEB_HOOKS: "false"
  INTEGRATIONS_SHELL_COMMANDS_FAILED_RETRY_DELAY: "60"
  INTEGRATIONS_SHELL_COMMANDS_ALLOW_PARAMETERS: "false"
  INTEGRATIONS_WEB_HOOKS_FAILED_RETRY_DELAY: "60"
  INTEGRATIONS_SHELL_COMMAND_01: ""
  INTEGRATIONS_SHELL_COMMAND_02: ""
  INTEGRATIONS_SHELL_COMMAND_03: ""
  INTEGRATIONS_SHELL_COMMAND_04: ""
  INTEGRATIONS_SHELL_COMMAND_05: ""
  INTEGRATIONS_SHELL_COMMAND_06: ""
  INTEGRATIONS_SHELL_COMMAND_07: ""
  INTEGRATIONS_SHELL_COMMAND_08: ""
  INTEGRATIONS_SHELL_COMMAND_09: ""
  INTEGRATIONS_SHELL_COMMAND_10: ""

  SHOW_EMAIL_SETTINGS: "true"

  SMTP_HOSTNAME: "smtp.example.com"
  SMTP_PORT: "587"
  SMTP_SSL: "STARTTLS"

  IMAP_HOSTNAME: "imap.example.com"
  IMAP_PORT: "993"
  IMAP_SSL: "SSL/TLS"

  POP3_HOSTNAME: "pop3.example.com"
  POP3_PORT: "995"
  POP3_SSL: "SSL/TLS"

